/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tni_interface;
import ij.IJ;
import java.awt.Color;
import ij.ImagePlus;
import ij.gui.HistogramWindow;
import javax.swing.*;
import java.awt.Image;
import ij.io.Opener;
import ij.process.ColorProcessor;
import ij.process.ImageConverter;
import ij.process.ImageProcessor;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import static java.lang.System.exit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;


/**
 *
 * @author Bill AHOUANDJINOU
 */
public class TNI_Interface extends javax.swing.JFrame {
    public ImagePlus imp, imp2; 
    public Image im1, im2;

    /**
     * Creates new form TNI_Interface
     */
    public TNI_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        openImage = new javax.swing.JMenuItem();
        saveImage = new javax.swing.JMenuItem();
        quitApp = new javax.swing.JMenuItem();
        applications = new javax.swing.JMenu();
        grayScale = new javax.swing.JMenuItem();
        rgb = new javax.swing.JMenuItem();
        imageInverter = new javax.swing.JMenuItem();
        gaborFilter = new javax.swing.JMenuItem();
        originalImageHistogram = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        enhancement = new javax.swing.JMenuItem();
        reframing = new javax.swing.JMenuItem();
        equalization = new javax.swing.JMenuItem();
        binarization = new javax.swing.JMenuItem();
        stamps = new javax.swing.JMenu();
        resizing = new javax.swing.JMenuItem();
        rotation = new javax.swing.JMenuItem();
        equalizationS = new javax.swing.JMenuItem();
        reinforcement = new javax.swing.JMenuItem();
        filter = new javax.swing.JMenu();
        gaussian = new javax.swing.JMenuItem();
        binomial = new javax.swing.JMenuItem();
        median = new javax.swing.JMenuItem();
        average = new javax.swing.JMenuItem();
        extractionMenu = new javax.swing.JMenu();
        borderDetection = new javax.swing.JMenu();
        sobel = new javax.swing.JMenuItem();
        gradient = new javax.swing.JMenuItem();
        laplacian = new javax.swing.JMenuItem();
        sobelxy = new javax.swing.JMenuItem();
        dynBinarization = new javax.swing.JMenuItem();
        extraction2 = new javax.swing.JMenuItem();
        fft = new javax.swing.JMenuItem();
        erosion = new javax.swing.JMenu();
        marthonImproved = new javax.swing.JMenuItem();
        lee = new javax.swing.JMenuItem();
        thoroughness = new javax.swing.JMenuItem();
        stripesExtraction = new javax.swing.JMenu();
        squaredFrame = new javax.swing.JMenuItem();
        hexagonalFrame = new javax.swing.JMenuItem();
        binarizationS = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(230, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Original Image");
        jLabel1.setFocusable(false);
        jScrollPane1.setViewportView(jLabel1);

        jLabel2.setForeground(new java.awt.Color(230, 44, 44));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Processed Image");
        jLabel2.setToolTipText("");
        jScrollPane2.setViewportView(jLabel2);

        file.setText("File");

        openImage.setText("Open Image");
        openImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                openImageMousePressed(evt);
            }
        });
        file.add(openImage);

        saveImage.setText("Save Image");
        saveImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saveImageMousePressed(evt);
            }
        });
        file.add(saveImage);

        quitApp.setText("Quit App");
        quitApp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                quitAppMousePressed(evt);
            }
        });
        file.add(quitApp);

        jMenuBar1.add(file);

        applications.setText("Applications");

        grayScale.setText("Gray Scale");
        grayScale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                grayScaleMousePressed(evt);
            }
        });
        applications.add(grayScale);

        rgb.setText("RGB");
        rgb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rgbMousePressed(evt);
            }
        });
        applications.add(rgb);

        imageInverter.setText("Image Inverter");
        imageInverter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imageInverterMousePressed(evt);
            }
        });
        applications.add(imageInverter);

        gaborFilter.setText("Gabor Filter");
        gaborFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gaborFilterMousePressed(evt);
            }
        });
        applications.add(gaborFilter);

        originalImageHistogram.setText("Histogram 1");
        originalImageHistogram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                originalImageHistogramMousePressed(evt);
            }
        });
        applications.add(originalImageHistogram);

        jMenuItem2.setText("Histogram 2");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        applications.add(jMenuItem2);

        enhancement.setText("Enhancement");
        enhancement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                enhancementMousePressed(evt);
            }
        });
        applications.add(enhancement);

        reframing.setText("Reframing");
        reframing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reframingMousePressed(evt);
            }
        });
        applications.add(reframing);

        equalization.setText("Equalization");
        equalization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                equalizationMousePressed(evt);
            }
        });
        applications.add(equalization);

        binarization.setText("Binarization");
        binarization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                binarizationMousePressed(evt);
            }
        });
        applications.add(binarization);

        jMenuBar1.add(applications);

        stamps.setText("Operations on Stamps");

        resizing.setText("Resizing");
        resizing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resizingMousePressed(evt);
            }
        });
        stamps.add(resizing);

        rotation.setText("Rotation");
        rotation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rotationMousePressed(evt);
            }
        });
        stamps.add(rotation);

        equalizationS.setText("Equalization");
        equalizationS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalizationSActionPerformed(evt);
            }
        });
        stamps.add(equalizationS);

        reinforcement.setText("Reinforcement");
        reinforcement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reinforcementMousePressed(evt);
            }
        });
        stamps.add(reinforcement);

        filter.setText("Filter");

        gaussian.setText("Gaussian");
        gaussian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gaussianMousePressed(evt);
            }
        });
        filter.add(gaussian);

        binomial.setText("Binomial");
        binomial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                binomialMousePressed(evt);
            }
        });
        filter.add(binomial);

        median.setText("Median");
        median.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                medianMousePressed(evt);
            }
        });
        filter.add(median);

        average.setText("Average");
        average.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                averageMousePressed(evt);
            }
        });
        filter.add(average);

        stamps.add(filter);

        extractionMenu.setText("Extraction");

        borderDetection.setText("Border Detection");

        sobel.setText("Sobel Scharr");
        sobel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sobelMousePressed(evt);
            }
        });
        borderDetection.add(sobel);

        gradient.setText("Gradient");
        borderDetection.add(gradient);

        laplacian.setText("Laplacian");
        laplacian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                laplacianMousePressed(evt);
            }
        });
        borderDetection.add(laplacian);

        sobelxy.setText("Sobel XY");
        sobelxy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sobelxyMousePressed(evt);
            }
        });
        borderDetection.add(sobelxy);

        extractionMenu.add(borderDetection);

        dynBinarization.setText("Dynamic Binarization");
        dynBinarization.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dynBinarizationMousePressed(evt);
            }
        });
        extractionMenu.add(dynBinarization);

        extraction2.setText("Extraction");
        extractionMenu.add(extraction2);

        stamps.add(extractionMenu);

        fft.setText("FFT");
        stamps.add(fft);

        erosion.setText("Erosion");

        marthonImproved.setText("Marthon improved");
        erosion.add(marthonImproved);

        lee.setText("Lee");
        erosion.add(lee);

        stamps.add(erosion);

        thoroughness.setText("Thoroughness");
        stamps.add(thoroughness);

        stripesExtraction.setText("Stripes Extraction");

        squaredFrame.setText("Squared Frame");
        squaredFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                squaredFrameMousePressed(evt);
            }
        });
        stripesExtraction.add(squaredFrame);

        hexagonalFrame.setText("Hexagonal Frame");
        hexagonalFrame.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                hexagonalFrameMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        stripesExtraction.add(hexagonalFrame);

        binarizationS.setText("Binarization");
        stripesExtraction.add(binarizationS);

        stamps.add(stripesExtraction);

        jMenuBar1.add(stamps);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grayScaleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grayScaleMousePressed
        // TODO add your handling code here:
        GrayScale();
    }//GEN-LAST:event_grayScaleMousePressed

    // A revoir //
    private void rgbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rgbMousePressed
        try {
            // TODO add your handling code here:
            RGB();
        } catch (IOException ex) {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rgbMousePressed

    private void imageInverterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageInverterMousePressed
        // TODO add your handling code here:
        ImageInverter();
    }//GEN-LAST:event_imageInverterMousePressed

    private void gaborFilterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gaborFilterMousePressed
        // TODO add your handling code here:
        GaborFilter();
    }//GEN-LAST:event_gaborFilterMousePressed

    private void originalImageHistogramMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_originalImageHistogramMousePressed
        // TODO add your handling code here:
        OriginalImageHistogram();
    }//GEN-LAST:event_originalImageHistogramMousePressed

    private void enhancementMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enhancementMousePressed
        // TODO add your handling code here:
        Enhancement();
    }//GEN-LAST:event_enhancementMousePressed

    private void reframingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reframingMousePressed
        // TODO add your handling code here:
        Reframing();
    }//GEN-LAST:event_reframingMousePressed

    private void equalizationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalizationMousePressed
        // TODO add your handling code here:
        Equalization();
    }//GEN-LAST:event_equalizationMousePressed

    private void binarizationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binarizationMousePressed
        // TODO add your handling code here:
        Binarization();
    }//GEN-LAST:event_binarizationMousePressed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        // TODO add your handling code here:
        ProcessedImageHistogram();
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void openImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openImageMousePressed
        // TODO add your handling code here:
        OpenImage();
    }//GEN-LAST:event_openImageMousePressed

    private void saveImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveImageMousePressed
        // TODO add your handling code here:
        SaveImage();
    }//GEN-LAST:event_saveImageMousePressed

    private void quitAppMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitAppMousePressed
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_quitAppMousePressed

    private void resizingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resizingMousePressed
        // TODO add your handling code here:
        Resizing();
    }//GEN-LAST:event_resizingMousePressed

    private void rotationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rotationMousePressed
        // TODO add your handling code here:
        Rotate();
    }//GEN-LAST:event_rotationMousePressed

    private void gaussianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gaussianMousePressed
        // TODO add your handling code here:
        Gaussian();
    }//GEN-LAST:event_gaussianMousePressed

    private void averageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_averageMousePressed
        // TODO add your handling code here:
        Average();
    }//GEN-LAST:event_averageMousePressed

    private void medianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medianMousePressed
        // TODO add your handling code here:
        Median();
    }//GEN-LAST:event_medianMousePressed

    private void binomialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binomialMousePressed
        // TODO add your handling code here:
        Binomial();
    }//GEN-LAST:event_binomialMousePressed

    private void squaredFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_squaredFrameMousePressed
        // TODO add your handling code here:
        SquaredFrame();
    }//GEN-LAST:event_squaredFrameMousePressed

    private void hexagonalFrameMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_hexagonalFrameMenuKeyPressed
        // TODO add your handling code here:
        HexagonalFrame();
    }//GEN-LAST:event_hexagonalFrameMenuKeyPressed

    private void dynBinarizationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dynBinarizationMousePressed
        // TODO add your handling code here:
        DynamicBinarization();
    }//GEN-LAST:event_dynBinarizationMousePressed

    private void reinforcementMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reinforcementMousePressed
        // TODO add your handling code here:
        Reinforcement();
    }//GEN-LAST:event_reinforcementMousePressed

    private void sobelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobelMousePressed
        // TODO add your handling code here:
        SobelScharr();
    }//GEN-LAST:event_sobelMousePressed

    private void laplacianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laplacianMousePressed
        // TODO add your handling code here:
        Laplacian();
    }//GEN-LAST:event_laplacianMousePressed

    private void sobelxyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sobelxyMousePressed
        // TODO add your handling code here:
        Sobelxy();
    }//GEN-LAST:event_sobelxyMousePressed

    private void equalizationSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalizationSActionPerformed
        // TODO add your handling code here:
        Equalization();
    }//GEN-LAST:event_equalizationSActionPerformed

    public void OpenImage()
    {
        Opener opener = new Opener();
        imp = opener.openImage("");
        ImageIcon image = new ImageIcon(imp.getOriginalFileInfo().getFilePath());
        jLabel1 = new JLabel (new ImageIcon(image.getImage()));
        jScrollPane1.setViewportView(jLabel1);
    }

    public void SaveImage()
    {
        try
        {
            String imageName = JOptionPane.showInputDialog("Enter file name");
            BufferedImage image = imp2.getBufferedImage();    
            ImageIO.write(image,"bmp",new File(imageName + ".png"));
            System.out.println("Image successfully saved.");
        } 
        catch (IOException e1)
        {
            System.out.println("Image not saved.");
        }
    }
        
    //NVG Function
    public void GrayScale()
    {
        ImagePlus image = new ImagePlus();
        Opener opener = new Opener();
        image = opener.openImage(imp.getOriginalFileInfo().getFilePath());// copie image
        new ImageConverter(image).convertToGray8();
        imp2 = image;
        im1 = image.getImage();
        ImageIcon image1 = new ImageIcon(im1);
        jLabel2 = new JLabel (new ImageIcon(image1.getImage()));
        jScrollPane2.setViewportView(jLabel2);
        //Enregistrer l'image au format PNG
        //File outFile = new File("grayScaleImage");
        //ImageIO.write(imagedst, "PNG", outFile);
        //System.out.println("Successfully converted");
        
    }
    
    // RGB Function // A revoir //
    public void RGB() throws IOException
    {
        BufferedImage image = ImageIO.read(new File(imp.getOriginalFileInfo().getFilePath()));
        int width = image.getWidth();
        int height = image.getHeight();

        BufferedImage imageR = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        BufferedImage imageG = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        BufferedImage imageB = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);

        for (int i = 0; i < width; i++) {
            for (int j = 0; j < height; j++) {
                Color pixelColor = new Color(image.getRGB(i, j));

                int r = pixelColor.getRed();
                int g = pixelColor.getGreen();
                int b = pixelColor.getBlue();

                imageR.setRGB(i, j, new Color(r, 0, 0).getRGB());
                imageG.setRGB(i, j, new Color(0, g, 0).getRGB());
                imageB.setRGB(i, j, new Color(0, 0, b).getRGB());
            }
        }

        ImageIO.write(imageR, "png", new File("imageR.png"));
        ImageIO.write(imageG, "png", new File("imageG.png"));
        ImageIO.write(imageB, "png", new File("imageB.png"));

        System.out.println("Red, Green, and Blue channel images saved successfully!");
    }
    
    // Image Inverter Function
    public void ImageInverter()
    {
        Opener opener = new Opener();
        ImagePlus image = opener.openImage(imp.getOriginalFileInfo().getFilePath());
        new ImageConverter(image).convertToGray8(); //Conversion en niveau de gris
        ImageProcessor ip = image.getProcessor();//Donne vie à l'image pour permettre d'y travailler // formatage
        ip.invert(); //Inversion de l'image
        imp2 = image;
        im2 = image.getImage();
        ImageIcon image2 = new ImageIcon(im2);
        jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
        jScrollPane2.setViewportView(jLabel2);
    }
    
    // Gabor Filter Function
    public void GaborFilter()
    {
        double F = 3.0 ; 
        double sigma_x= 4 ;
        double sigma_y= 16 ;
        ImagePlus image = new ImagePlus();
        Opener opener= new Opener();
        image = opener.openImage(imp.getOriginalFileInfo().getFilePath());
        new ImageConverter(image).convertToGray8();
        ImageProcessor ip = image.getProcessor();
        int width = ip.getWidth();              
        int height = ip.getHeight(); 
        double sigma_x2 = sigma_x*sigma_x;
        double sigma_y2 = sigma_y*sigma_y;
        double theta = Math.PI/(double) 6;
        for (int x = 0 ; x < width ; x++)
        {
            for(int y=0 ; y<height ; y++)
            {
                double xPrime = (double) x*Math.cos(theta)+(double) y*Math.sin(theta) ;
                double yPrime = (double) y*Math.cos(theta)-(double) x*Math.sin(theta) ;
                double a = 1.0 / ( 2.0*Math.PI*sigma_x*sigma_y) * Math.exp(-0.5 *(xPrime*xPrime / sigma_x2+yPrime *yPrime / sigma_y2)) ;
                float c = (float) (a*Math.cos(2.0*Math.PI*(F*xPrime))) ;
            }
        }  
        imp2 = image;                
        im1 = image.getImage();
        ImageIcon image1 = new ImageIcon(im1);
        jLabel2 = new JLabel (new ImageIcon(image1.getImage()));
        jScrollPane2.setViewportView(jLabel2);
    }
    
    // Histogram Drawing Function
    public void OriginalImageHistogram()
    {
        HistogramWindow histo = new HistogramWindow (imp);
        histo.setVisible(true);
    }
    
    // Histogram
    public void ProcessedImageHistogram()
    {
        HistogramWindow histo = new HistogramWindow (imp2);
        histo.setVisible(true);
    }
    
    // Enhancement
    public void Enhancement()
    {
        int a = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter the min value"));
        int b = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter the max value"));
        ImagePlus image = new ImagePlus();
        Opener opener= new Opener();
        image = opener.openImage(imp.getOriginalFileInfo().getFilePath());
        new ImageConverter(image).convertToGray8();
        ImageProcessor ip = image.getProcessor();
        int width = image.getWidth();
        int height = image.getHeight();
        for (int i = 0; i < width; i++)
        {
            for (int j = 0; j < height; j++)
            {
                if (ip.get(i,j) > 0 && ip.get(i,j) < a)
                {
                    int c  = b*ip.get(i,j)/a;
                    ip.set(i,j,c);
                }
                else if (ip.get(i,j) > a && ip.get(i,j) < 255)
                {
                    int c  = ((255-b)*ip.get(i,j) + 255*(b-a))/(255-a);
                    ip.set(i,j,c);
                }
            }
        }
        imp2 = image;
        im2 = image.getImage();
        ImageIcon image2 = new ImageIcon(im2);
        jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
        jScrollPane2.setViewportView(jLabel2);
    }
    
    // Reframing
    public void Reframing()
    {
        int a = Integer.parseInt(JOptionPane.showInputDialog(null,"Enter the min value"));
        int b = Integer.parseInt(JOptionPane.showInputDialog(null,"Enter the max value"));
        ImagePlus image = new ImagePlus();
        Opener opener= new Opener();
        image = opener.openImage(imp.getOriginalFileInfo().getFilePath());
        int width = image.getWidth();
        int height = image.getHeight();
        ImageProcessor ip = image.getProcessor();
        for (int i = 0; i < width; i++)
        {
            for (int j = 0; j < height; j++)
            {
                if (ip.get(i,j) < a)
                {
                    ip.set(i,j,0);
                }
                else if (ip.get(i,j) > b)
                {
                    ip.set(i,j,255);
                }
                else
                {
                    int c = 255*(ip.get(i,j)-a/b-a);
                    ip.set(i,j,c);
                }
            }
        }
        imp2 = image;
        im2 = image.getImage();
        ImageIcon image2 = new ImageIcon(im2);
        jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
        jScrollPane2.setViewportView(jLabel2);
    }
    
    // No set yet //
    public void Equalization()
    {
        Opener opener = new Opener();
        ImagePlus image = opener.openImage(imp.getOriginalFileInfo().getFilePath());
        // image.show();
        // IJ.wait(1500); //Temporisation de 1.5 seconde
        new ImageConverter(image).convertToGray8(); 
        ImageProcessor ip = image.getProcessor(); 
        IJ.log("Grey-level before inversion = " + ip.get(100, 500)); 
        image.show(); 
        IJ.wait(1500); 
        ip.invert(); 
        // image.show();
        IJ.log("Grey-level after inversion = " + ip.get(100,500));
        imp2 = image;
        im2 = image.getImage();
        ImageIcon image2 = new ImageIcon(im2);
        jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
        jScrollPane2.setViewportView(jLabel2);
    }
    
    // A revoir //
    public void Binarization()
    { 
        int threshold = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter the threshold value"));
        ImagePlus image = new ImagePlus();
        Opener opener= new Opener();
        image = opener.openImage(imp.getOriginalFileInfo().getFilePath());     
        new ImageConverter(image).convertToGray8();
        int width = image.getWidth();
        int height = image.getHeight();
        ImageProcessor ip = image.getProcessor();
        for (int i = 0; i < width; i++)
        {
            for (int j = 0; j < height; j++)
            {
                if (ip.get(i,j) < threshold)
                {
                    ip.set(i,j,0);
                }
                else
                {
                    ip.set(i,j,255);
                }
            }
        }
        imp2 = image;
        im2 = image.getImage();
        ImageIcon image2 = new ImageIcon(im2);
        jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
        jScrollPane2.setViewportView(jLabel2);
    }
    
    // Resizing A revoir //
    public void Resizing()
    {
        try {
            ImagePlus imageP = new ImagePlus(imp.getOriginalFileInfo().getFilePath());
            BufferedImage originalImage = imageP.getBufferedImage();

            int w = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter Width: "));
            int h = Integer.parseInt(JOptionPane.showInputDialog(null, "Enter Height: "));

            BufferedImage resizedImage = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2d = resizedImage.createGraphics();
            g2d.drawImage(originalImage.getScaledInstance(w, h, Image.SCALE_SMOOTH), 0, 0, w, h, null);
            g2d.dispose();

            String resImage = JOptionPane.showInputDialog("Enter filename for resized image (without extension): ");
            String outputPath = resImage + ".png";

            ImageIO.write(resizedImage, "png", new File(outputPath));
            System.out.println("(Resizing) Image saved: " + outputPath);

            ImagePlus resizedImageP = new ImagePlus(outputPath);
            resizedImageP.show();
            imp2 = imageP;
            im2 = imageP.getImage();
            ImageIcon image2 = new ImageIcon(im2);
            jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
            jScrollPane2.setViewportView(jLabel2);

        } catch (IOException ex) {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter numeric values for width and height.");
        }
        
    }
    
    // Rotation //
    public void Rotate()
    {
        try
        {
            ImagePlus imageP = new ImagePlus(imp.getOriginalFileInfo().getFilePath());
            BufferedImage image = imageP.getBufferedImage();

            double angle = Double.parseDouble(JOptionPane.showInputDialog(null, "Enter Rotation Angle (degrees): "));

            int w = image.getWidth();
            int h = image.getHeight();

            AffineTransform tx = new AffineTransform();
            tx.rotate(Math.toRadians(angle), w / 2.0, h / 2.0);

            AffineTransformOp op = new AffineTransformOp(tx, AffineTransformOp.TYPE_BILINEAR);
            BufferedImage rotatedImage = op.filter(image, null);

            String rotImage = JOptionPane.showInputDialog("Enter filename for rotated image (without extension): ");
            String outputPath = rotImage + ".png";

            ImageIO.write(rotatedImage, "png", new File(outputPath));
            System.out.println("(Rotation) Image saved: " + outputPath);

            ImagePlus rotatedImageP = new ImagePlus(outputPath);
            rotatedImageP.show();
            // ImagePlus imageP1 = opener1.openImage(name);
            imp2 = imageP;
            im2 = rotatedImageP.getImage();
            ImageIcon image2 = new ImageIcon(im2);
            jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
            jScrollPane2.setViewportView(jLabel2);
        }
        catch (IOException ex)
        {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Reinforcement
    public void Reinforcement()
    {
        try
        {
            /* L'image sur laquelle on travaille */
            Opener opener = new Opener();
            ImagePlus imageP = opener.openImage(imp.getOriginalFileInfo().getFilePath());
            BufferedImage image= imageP.getBufferedImage();
            
            /* Définition du noyau */
            Kernel kernel = new Kernel(3, 3, new float[]{0,-1,0,
                                                        -1,5,-1,
                                                        0,-1,0});
            
            /* Création de la convolution associée */
            ConvolveOp convolution = new ConvolveOp(kernel);
            
            /* Application de la convolution à l'image */
            BufferedImage resultat = convolution.filter(image, null);
            String reiImage = JOptionPane.showInputDialog("Image convoled reinforcement : ");
            ImageIO.write(resultat,"bmp",new File(reiImage + ".png"));
            System.out.println("(Reinforcement) Image saved.");
            Opener opener1 = new Opener();
            String name = reiImage + ".png";
            ImagePlus imageP1 = opener1.openImage(name);
            imp2 = imageP1;
            im2 = imageP1.getImage();
            ImageIcon image2 = new ImageIcon(im2);
            jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
            jScrollPane2.setViewportView(jLabel2);
        }
        catch (IOException ex)
        {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Gaussian Filter
    public void Gaussian()
    {
        try
        {
            Opener opener = new Opener();
            ImagePlus imageP = opener.openImage(imp.getOriginalFileInfo().getFilePath());
            BufferedImage image= imageP.getBufferedImage();
            /* Définition du noyau */
            Kernel kernel = new Kernel(3, 3, new float[]{1/16,2/16,1/16,
                                                         2/16,4,2/16,
                                                         1/16,2/16,1/16}); 
            /* Création de la convolution associée */
            ConvolveOp convolution = new ConvolveOp(kernel);
            //BufferedImage image2 = new BufferedImage(image);
            /* Application de la convolution à l'image */
            BufferedImage resultat = convolution.filter(image, null);
            String gauImage = JOptionPane.showInputDialog("Image convoled gaussian : ");
            ImageIO.write(resultat,"bmp",new File(gauImage + ".png"));
            System.out.println("(Gaussian) Image saved.");
            Opener opener1 = new Opener();
            String name = gauImage + ".png";
            ImagePlus imageP1 = opener1.openImage(name);
            imp2 = imageP1;
            im2 = imageP1.getImage();
            ImageIcon image2 = new ImageIcon(im2);
            jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
            jScrollPane2.setViewportView(jLabel2);
        }
        catch (IOException ex)
        {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Binomial Filter //
    public void Binomial()
    {
        try
        {
            Opener opener = new Opener();
            ImagePlus imageP = opener.openImage(imp.getOriginalFileInfo().getFilePath());
            BufferedImage image = imageP.getBufferedImage();

            // Define the binomial filter kernel (corrected float division)
            float[] kernelData = {
                1f / 9, 1f / 9, 1f / 9,
                1f / 9, 1f / 9, 1f / 9,
                1f / 9, 1f / 9, 1f / 9
            };
            Kernel kernel = new Kernel(3, 3, kernelData);

            ConvolveOp convolution = new ConvolveOp(kernel, ConvolveOp.EDGE_NO_OP, null);
            
            BufferedImage resultat = convolution.filter(image, null);

            String binImage = JOptionPane.showInputDialog("Enter filename for binomial filtered image:");
            String outputPath = binImage + ".png";

            ImageIO.write(resultat, "png", new File(outputPath));
            System.out.println("(Binomial) Image saved: " + outputPath);

            ImagePlus imageP1 = new ImagePlus(outputPath);
            imageP1.show();
            // ImagePlus imageP1 = opener1.openImage(name);
            imp2 = imageP1;
            im2 = imageP1.getImage();
            ImageIcon image2 = new ImageIcon(im2);
            jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
            jScrollPane2.setViewportView(jLabel2);
        }
        catch (IOException ex)
        {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    // Laplacian
    public void Laplacian()
    {
        try
        {
            Opener opener = new Opener();
            ImagePlus imageP = opener.openImage(imp.getOriginalFileInfo().getFilePath());
            BufferedImage image = imageP.getBufferedImage();

            float[] laplacianKernel = {
                0f,  1f,  0f,
                1f, -4f,  1f,
                0f,  1f,  0f
            };
            Kernel kernel = new Kernel(3, 3, laplacianKernel);

            ConvolveOp convolution = new ConvolveOp(kernel, ConvolveOp.EDGE_NO_OP, null);
            BufferedImage resultat = convolution.filter(image, null);

            String lapImage = JOptionPane.showInputDialog("Enter filename for Laplacian filtered image:");
            String outputPath = lapImage + ".png";

            ImageIO.write(resultat, "png", new File(outputPath));
            System.out.println("(Laplacian) Image saved: " + outputPath);
            ImagePlus imageP1 = new ImagePlus(outputPath);
            imageP1.show();
            // ImagePlus imageP1 = opener.openImage(name);
            imp2 = imageP1;
            im2 = imageP1.getImage();
            ImageIcon image2 = new ImageIcon(im2);
            jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
            jScrollPane2.setViewportView(jLabel2);
        }
        catch (IOException ex)
        {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    // Average Filter
    public void Average()
    {
        try
        {
            Opener opener = new Opener();
            ImagePlus imageP = opener.openImage(imp.getOriginalFileInfo().getFilePath());
            BufferedImage image= imageP.getBufferedImage();
                    /* Définition du noyau */
            Kernel kernel = new Kernel(3, 3, new float[]{1f/9,1f/9,1f/9,
                                                         1f/9,1f/9,1f/9,
                                                         1f/9,1f/9,1f/9});                     
                    /* Création de la convolution associée */
            ConvolveOp convolution = new ConvolveOp(kernel);
            //BufferedImage image2 = new BufferedImage(image);
                    /* Application de la convolution à l'image */
            BufferedImage resultat = convolution.filter(image, null);
            String aveImage = JOptionPane.showInputDialog("Image convoled average : ");
            ImageIO.write(resultat,"bmp",new File(aveImage + ".png"));
            System.out.println("(Average) Image saved.");
            Opener opener1 = new Opener();
            String name = aveImage + ".png";
            ImagePlus imageP1 = opener1.openImage(name);
            imp2 = imageP1;
            im2 = imageP1.getImage();
            ImageIcon image2 = new ImageIcon(im2);
            jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
            jScrollPane2.setViewportView(jLabel2);
        }
        catch (IOException ex)
        {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    //Median Filter
    public void Median()
    {
        try
        {
            Opener opener = new Opener();
            ImagePlus imageP = opener.openImage(imp.getOriginalFileInfo().getFilePath());
            BufferedImage image= imageP.getBufferedImage();

                    /* Définition du noyau */
            Kernel kernel = new Kernel(3, 3, new float[]{0,1,0,1,-4,1,0,1,0});
                    /* Création de la convolution associée */
            ConvolveOp convolution = new ConvolveOp(kernel);
            //BufferedImage image2 = new BufferedImage(image);
                    /* Application de la convolution à l'image */
            BufferedImage resultat = convolution.filter(image, null);
            String medImage = JOptionPane.showInputDialog("Image convoled median : ");
            ImageIO.write(resultat,"bmp",new File(medImage + ".png"));
            System.out.println("(Median) Image saved.");
            Opener opener1 = new Opener();
            String name = medImage + ".png";
            ImagePlus imageP1 = opener1.openImage(name);
            imp2 = imageP1;
            im2 = imageP1.getImage();
            ImageIcon image2 = new ImageIcon(im2);
            jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
            jScrollPane2.setViewportView(jLabel2);
        }
        catch (IOException ex)
        {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Border Detection
    public void Sobelxy()
    {
        try
        {
            Opener opener = new Opener();
            ImagePlus imageP = opener.openImage(imp.getOriginalFileInfo().getFilePath());
            BufferedImage image= imageP.getBufferedImage();
            /* Définition du noyau */
            Kernel kernelx = new Kernel(3, 3, new float[]{1,0,-1,
                                                         2,0,-2,
                                                         1,0,-1});
            Kernel kernely = new Kernel(3, 3, new float[]{1,2,1,
                                                         0,0,0,
                                                         -1,-2,-1}); 
            /* Création de la convolution associée */
            ConvolveOp convolutionx = new ConvolveOp(kernelx);
            ConvolveOp convolutiony = new ConvolveOp(kernelx);
            //BufferedImage image2 = new BufferedImage(image);
            /* Application de la convolution à l'image */
            BufferedImage resultatx = convolutionx.filter(image, null);
            BufferedImage resultaty = convolutiony.filter(image, null);
            String sobImagex = JOptionPane.showInputDialog("Image convoled Sobel(X) : ");
            ImageIO.write(resultatx,"bmp",new File(sobImagex + ".png"));
            System.out.println("(Sobel X) Image saved.");
            Opener opener1 = new Opener();
            String namex = sobImagex + ".png";
            String sobImagey = JOptionPane.showInputDialog("Image convoled Sobel(Y) : ");
            ImageIO.write(resultaty,"bmp",new File(sobImagey + ".png"));
            System.out.println("(Sobel Y) Image saved.");
            String namey = sobImagey + ".png";
            //ImagePlus imP = Math.sqrt(resultatx*resultaty);
            ImagePlus imageP1 = opener1.openImage(namex);
            imp2 = imageP1;
            im2 = imageP1.getImage();
            ImageIcon image2 = new ImageIcon(im2);
            jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
            jScrollPane2.setViewportView(jLabel2);
        }
        catch (IOException ex)
        {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // SobelScharr
    public void SobelScharr()
    {
        try
        {
            Opener opener = new Opener();
            ImagePlus imageP = opener.openImage(imp.getOriginalFileInfo().getFilePath());
            BufferedImage image= imageP.getBufferedImage();
            /* Définition du noyau */
            Kernel kernel = new Kernel(3, 3, new float[]{-3,0,3,
                                                         -10,0,10,
                                                         3,0,3}); 
            /* Création de la convolution associée */
            ConvolveOp convolution = new ConvolveOp(kernel);
            //BufferedImage image2 = new BufferedImage(image);
            /* Application de la convolution à l'image */
            BufferedImage resultat = convolution.filter(image, null);
            String sobImage = JOptionPane.showInputDialog("Image convoled SobelScharr : ");
            ImageIO.write(resultat,"bmp",new File(sobImage + ".png"));
            System.out.println("(SobelScharr) Image saved.");
            Opener opener1 = new Opener();
            String name = sobImage + ".png";
            ImagePlus imageP1 = opener1.openImage(name);
            imp2 = imageP1;
            im2 = imageP1.getImage();
            ImageIcon image2 = new ImageIcon(im2);
            jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
            jScrollPane2.setViewportView(jLabel2);
        }
        catch (IOException ex)
        {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //Dynamic Binarization
    public void DynamicBinarization()
    {
        try
        {
            Opener opener = new Opener();
            ImagePlus imageP = opener.openImage(imp.getOriginalFileInfo().getFilePath());
            new ImageConverter(imageP).convertToGray8();
            ImageProcessor ip = imageP.getProcessor();
            int w = imageP.getWidth();
            int h = imageP.getHeight();
            for(int i = 0; i < h; i++)
            {
                double thresholdValue = 0;
                for(int j = 0; j < w; j++)
                {
                    thresholdValue += ip.get(i,j);
                }
                thresholdValue = thresholdValue/w;
                for(int j = 0; j < w; j++)
                {
                    if(ip.get(i, j) < thresholdValue)
                    {
                        ip.set(i, j, 0);
                    }
                    else
                    {
                        ip.set(i, j, 255);
                    }
                }
            }
            ImagePlus iP = new ImagePlus("Result",ip);
            String dynBinImage = JOptionPane.showInputDialog("Image dynamic binarized : ");
            ImageIO.write((RenderedImage) iP,"bmp",new File(dynBinImage + ".png"));
            System.out.println("(Binomial) Image saved.");
            Opener opener1 = new Opener();
            String name = dynBinImage + ".png";
            ImagePlus imageP1 = opener1.openImage(name);
            imp2 = imageP1;
            im2 = imageP1.getImage();
            ImageIcon image2 = new ImageIcon(im2);
            jLabel2 = new JLabel (new ImageIcon(image2.getImage()));
            jScrollPane2.setViewportView(jLabel2);
        }
        catch (IOException ex)
        {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    //SquaredFrame
    public void SquaredFrame()
    {
        try
        {
            Opener opener = new Opener();
            ImagePlus imageP = opener.openImage(imp.getOriginalFileInfo().getFilePath());
            ImageProcessor ip = imageP.getProcessor();
            int w = imageP.getWidth();
            int h = imageP.getHeight();
            for(int i = 1; i <= h; i++)
            {
                double s = 0;
                for(int j = 1; j <= w; j++)
                {
                    s = (ip.get(i-1,j-1) + ip.get(i,j-1) + ip.get(i+1,j-1) + ip.get(i-1,j) + ip.get(i+1,j) + ip.get(i-1,j+1) + ip.get(i,j+1) + ip.get(i+1,j+1))/8;
                    if(ip.get(i,j) < s)
                    {
                        ip.set(i,j,0);
                    }
                    else
                    {
                        ip.set(i,j,255);
                    }
                }
            }
            
            BufferedImage image = ip.getBufferedImage();
            String squImage = JOptionPane.showInputDialog("Image framing squared : ");
            ImageIO.write(image,"bmp",new File(squImage + ".png"));
            System.out.println("(Square Frame) Image saved.");
        }
        catch (IOException ex)
        {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    //Hexagonal frame
    public void HexagonalFrame()
    {
        try
        {
            Opener opener = new Opener();
            ImagePlus imageP = opener.openImage(imp.getOriginalFileInfo().getFilePath());
            ImageProcessor ip = imageP.getProcessor();
            int w = imageP.getWidth();
            int h = imageP.getHeight();
            for(int i = 2; i <= h; i++)
            {
                double s = 0;
                for(int j = 2; j <= w; j++)
                {
                    s = (ip.get(i-1,j-1) + ip.get(i-1,j+1) + ip.get(i,j-2) + ip.get(i,j+2) + ip.get(i+1,j-1) + ip.get(i+1,j+1))/6;
                    if(ip.get(i,j) < s)
                    {
                        ip.set(i,j,0);
                    }
                    else
                    {
                        ip.set(i,j,255);
                    }
                }
            }
            
            BufferedImage image = ip.getBufferedImage();
            String squImage = JOptionPane.showInputDialog("Image framing squared : ");
            ImageIO.write(image,"bmp",new File(squImage + ".png"));
            System.out.println("(Square Frame) Image saved.");
        }
        catch (IOException ex)
        {
            Logger.getLogger(TNI_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TNI_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TNI_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TNI_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TNI_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TNI_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu applications;
    private javax.swing.JMenuItem average;
    private javax.swing.JMenuItem binarization;
    private javax.swing.JMenuItem binarizationS;
    private javax.swing.JMenuItem binomial;
    private javax.swing.JMenu borderDetection;
    private javax.swing.JMenuItem dynBinarization;
    private javax.swing.JMenuItem enhancement;
    private javax.swing.JMenuItem equalization;
    private javax.swing.JMenuItem equalizationS;
    private javax.swing.JMenu erosion;
    private javax.swing.JMenuItem extraction2;
    private javax.swing.JMenu extractionMenu;
    private javax.swing.JMenuItem fft;
    private javax.swing.JMenu file;
    private javax.swing.JMenu filter;
    private javax.swing.JMenuItem gaborFilter;
    private javax.swing.JMenuItem gaussian;
    private javax.swing.JMenuItem gradient;
    private javax.swing.JMenuItem grayScale;
    private javax.swing.JMenuItem hexagonalFrame;
    private javax.swing.JMenuItem imageInverter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem laplacian;
    private javax.swing.JMenuItem lee;
    private javax.swing.JMenuItem marthonImproved;
    private javax.swing.JMenuItem median;
    private javax.swing.JMenuItem openImage;
    private javax.swing.JMenuItem originalImageHistogram;
    private javax.swing.JMenuItem quitApp;
    private javax.swing.JMenuItem reframing;
    private javax.swing.JMenuItem reinforcement;
    private javax.swing.JMenuItem resizing;
    private javax.swing.JMenuItem rgb;
    private javax.swing.JMenuItem rotation;
    private javax.swing.JMenuItem saveImage;
    private javax.swing.JMenuItem sobel;
    private javax.swing.JMenuItem sobelxy;
    private javax.swing.JMenuItem squaredFrame;
    private javax.swing.JMenu stamps;
    private javax.swing.JMenu stripesExtraction;
    private javax.swing.JMenuItem thoroughness;
    // End of variables declaration//GEN-END:variables
}
